task: classification
model: SimpleCNN
train_path: ./data/processed/cancer_dataset/train
validation_path: ./data/processed/cancer_dataset/val
test_path: ./data/processed/cancer_dataset/test
epochs: 5
evaluation: True
save_path: results/best_model.pth
